SELECT HOUR(DATETIME) AS hour, count(DATETIME) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) BETWEEN 9 AND 19 group by hour ORDER BY HOUR;

SELECT SUBSTRING(DATETIME,12, 2) AS 'HOUR', COUNT(*) AS 'COUNT'
FROM ANIMAL_OUTS
GROUP BY SUBSTRING(DATETIME,12, 2)
HAVING HOUR >= 9 AND HOUR <= 19
ORDER BY HOUR